In [ ]:
import pandas as pd

print(':-) ')
df = pd.read_csv("datasource/data.csv")   # erzeugt ein dataframe von data.csv
df

#korelation von spalten, gucken ob korrelationen sind
#EDA in extra py. file abtrennen

#trenne doch mal die geschlechter und prüfe die ergebnisse gegeneinander: ticken mail und femail gleich?

#plots ansehen und belege machen
#paiplot ausprobieren um kor zu zeigen
#kontinuierlich daten (boxplot), #unkontinuirlich daten
#readme muss mit rein, erklärung wie zu laufen bringen, data nicht in git 

#nullanalyser (nur 0 werte aus daten raus)

#muss die env / venv ins GIT

#sns.countplot um alle targets anzuzeigen - beispiel anuar - balkendiagramm
#sns.boxplot

#nach eda gecleante datei speichern und weitereverwenden

:-)

,N6,N8,N7,N1,N9,N10,N3,N5,E3,N2,...,E4,age,C4,E1,A4,E10,E9,gender,hand,target
0,1,1,1,1,1,1,2,1,5,5,...,2,53,1,4,5,1,5,Male,Right,Resilient
1,4,2,3,2,2,4,4,3,3,3,...,3,46,2,2,4,5,1,Female,Right,Moderate
2,5,5,5,5,5,5,5,5,1,1,...,4,14,1,5,5,1,5,Female,Right,Moderate
3,5,5,5,5,4,5,4,4,2,4,...,4,19,5,2,4,5,4,Female,Right,Overcontroller
4,3,3,3,3,3,4,3,3,3,3,...,3,25,3,3,5,5,3,Female,Right,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19714,5,4,4,5,4,4,5,4,3,3,...,5,15,3,1,5,5,1,Female,Right,Overcontroller
19715,2,2,2,2,2,2,2,3,2,4,...,3,37,2,2,4,4,4,Female,Right,Resilient
19716,5,5,5,5,5,5,5,5,4,1,...,5,16,5,2,2,5,1,Male,Right,Overcontroller
19717,4,4,4,4,4,4,5,4,2,3,...,3,16,2,1,4,5,4,Male,Right,Overcontroller
19718,3,3,4,5,2,4,5,3,1,2,...,5,35,4,2,3,4,2,Male,Right,Overcontroller

In [10]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(df):
    # Sort by column: 'age' (descending)
    df = df.sort_values(['age'], ascending=[False])
    # Filter rows based on column: 'age'
    df = df[df['age'] < 100]
    return df

df_clean = clean_data(df.copy())
df_clean.info()
df_clean.head(100)

<class 'pandas.DataFrame'>
Index: 19635 entries, 14145 to 19693
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N6      19635 non-null  int64
 1   N8      19635 non-null  int64
 2   N7      19635 non-null  int64
 3   N1      19635 non-null  int64
 4   N9      19635 non-null  int64
 5   N10     19635 non-null  int64
 6   N3      19635 non-null  int64
 7   N5      19635 non-null  int64
 8   E3      19635 non-null  int64
 9   N2      19635 non-null  int64
 10  E5      19635 non-null  int64
 11  N4      19635 non-null  int64
 12  E7      19635 non-null  int64
 13  E4      19635 non-null  int64
 14  age     19635 non-null  int64
 15  C4      19635 non-null  int64
 16  E1      19635 non-null  int64
 17  A4      19635 non-null  int64
 18  E10     19635 non-null  int64
 19  E9      19635 non-null  int64
 20  gender  19611 non-null  str
 21  hand    19537 non-null  str
 22  target  19635 non-null  str
dtypes: int64(20), str(3)
memory usage: 3.6 MB

,N6,N8,N7,N1,N9,N10,N3,N5,E3,N2,...,E4,age,C4,E1,A4,E10,E9,gender,hand,target
14145,4,2,2,4,4,4,4,4,4,4,...,2,99,3,3,5,2,3,Other,Right,Moderate
11468,3,3,3,3,3,3,5,3,5,3,...,5,97,5,3,5,3,3,Female,Left,Undercontroller
8223,5,5,5,5,5,5,5,5,5,5,...,5,92,5,5,5,5,5,Male,Both,Moderate
11572,3,2,3,3,2,3,2,3,4,4,...,3,80,3,3,4,2,4,Female,Right,Moderate
15191,4,4,4,4,4,2,4,3,3,3,...,3,79,1,2,5,2,2,Female,Right,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8027,3,4,4,3,4,3,4,4,4,2,...,3,67,3,4,4,2,5,Male,Right,Moderate
18962,3,3,4,3,4,1,5,4,4,3,...,4,67,4,4,5,3,3,Female,Left,Moderate
12892,4,1,1,3,2,1,4,2,5,3,...,5,67,1,4,3,1,5,Female,Right,Resilient
946,2,1,1,2,2,1,4,1,3,5,...,5,67,1,1,4,5,1,Male,Right,Resilient
12592,1,2,2,2,1,5,2,1,5,5,...,2,67,3,2,5,3,4,Male,Right,Resilient